#!/usr/bin/env node
// Fetch a curated snapshot of the user's public GitHub presence and bake it
// into lib/keshav-context.generated.ts so the chat assistant can answer
// nuanced questions about specific repos without a runtime API call.
//
// Runs as a `prebuild` script (see package.json) so production builds always
// ship with fresh data. Falls back to writing an empty file if the API is
// unreachable — the chat still works, just without the GitHub flavour.
//
// Optional auth: set GITHUB_TOKEN to lift the unauthenticated 60 req/hr limit
// to 5000 req/hr. The token is only ever read on the server / build machine.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, "../lib/keshav-context.generated.ts");
const USERNAME = process.env.GITHUB_USERNAME || "Keshav-Madhav";
const TOKEN = process.env.GITHUB_TOKEN || "";
const MAX_REPOS = 25;
const README_CHAR_LIMIT = 1500;

const headers = {
  "Accept": "application/vnd.github+json",
  "User-Agent": "keshav-portfolio-build",
  ...(TOKEN ? { Authorization: `Bearer ${TOKEN}` } : {}),
};

async function gh(path) {
  const res = await fetch(`https://api.github.com${path}`, { headers });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} on ${path}`);
  return res.json();
}

async function fetchReadme(owner, repo) {
  try {
    const res = await fetch(
      `https://api.github.com/repos/${owner}/${repo}/readme`,
      { headers: { ...headers, Accept: "application/vnd.github.raw" } },
    );
    if (!res.ok) return "";
    const text = await res.text();
    // Strip badges + HTML comments, collapse whitespace, truncate.
    return text
      .replace(/!\[[^\]]*\]\([^)]*\)/g, "") // images / badges
      .replace(/<!--[\s\S]*?-->/g, "")
      .replace(/<[^>]+>/g, "")
      .replace(/\n{3,}/g, "\n\n")
      .trim()
      .slice(0, README_CHAR_LIMIT);
  } catch {
    return "";
  }
}

function escapeBackticks(s) {
  return String(s).replace(/`/g, "\\`").replace(/\${/g, "\\${");
}

function toBuildOutput(payload) {
  return `// AUTO-GENERATED by scripts/fetch-github.mjs — do not edit by hand.
// Last fetched: ${payload.fetchedAt}

export const GITHUB_CONTEXT = \`${escapeBackticks(payload.markdown)}\`;
`;
}

function writeEmpty(reason) {
  const out = `// AUTO-GENERATED by scripts/fetch-github.mjs — do not edit by hand.
// Skipped: ${reason}

export const GITHUB_CONTEXT = "";
`;
  fs.writeFileSync(OUT, out);
}

async function main() {
  console.log(`[github] fetching @${USERNAME} (auth: ${TOKEN ? "yes" : "no"})`);

  let user, repos;
  try {
    [user, repos] = await Promise.all([
      gh(`/users/${USERNAME}`),
      gh(`/users/${USERNAME}/repos?per_page=100&sort=pushed`),
    ]);
  } catch (err) {
    console.warn(`[github] fetch failed (${err.message}), writing empty context`);
    writeEmpty(err.message);
    return;
  }

  // Curate: drop forks, sort by stars + recency, take top N.
  const curated = repos
    .filter((r) => !r.fork && !r.archived)
    .sort((a, b) => (b.stargazers_count - a.stargazers_count) ||
                     (Date.parse(b.pushed_at) - Date.parse(a.pushed_at)))
    .slice(0, MAX_REPOS);

  console.log(`[github] curated ${curated.length} of ${repos.length} repos`);

  // Fetch READMEs in parallel (cap parallelism via Promise.allSettled in batches).
  const readmes = [];
  for (let i = 0; i < curated.length; i += 5) {
    const batch = curated.slice(i, i + 5);
    const results = await Promise.allSettled(
      batch.map((r) => fetchReadme(USERNAME, r.name)),
    );
    readmes.push(...results.map((r) => (r.status === "fulfilled" ? r.value : "")));
  }

  const lines = [];
  lines.push(`# Live GitHub snapshot`);
  lines.push("");
  lines.push(`**Profile**: ${user.html_url}`);
  if (user.bio) lines.push(`**GitHub bio**: ${user.bio}`);
  lines.push(`**Public repos**: ${user.public_repos} · **Followers**: ${user.followers}`);
  lines.push("");
  lines.push("# Top repositories");
  lines.push("");

  for (let i = 0; i < curated.length; i++) {
    const r = curated[i];
    lines.push(`## ${r.name} (${r.language ?? "—"}, ★${r.stargazers_count})`);
    if (r.description) lines.push(r.description);
    lines.push(`URL: ${r.html_url}`);
    if (r.homepage) lines.push(`Live: ${r.homepage}`);
    if (r.topics?.length) lines.push(`Topics: ${r.topics.join(", ")}`);
    if (readmes[i]) {
      lines.push("");
      lines.push("**README excerpt**:");
      lines.push(readmes[i]);
    }
    lines.push("");
  }

  const payload = {
    fetchedAt: new Date().toISOString(),
    markdown: lines.join("\n"),
  };

  fs.writeFileSync(OUT, toBuildOutput(payload));
  const sizeKB = (fs.statSync(OUT).size / 1024).toFixed(1);
  console.log(`[github] wrote ${OUT} (${sizeKB} KB)`);
}

main().catch((err) => {
  console.warn(`[github] unexpected error: ${err.message}`);
  writeEmpty(err.message);
});
